import type { ScreeningResult } from '@/types'

const NOW = new Date().toISOString()
const BATCH = 'sample-demo-batch'

export const SAMPLE_RESULTS: ScreeningResult[] = [
  {
    id: 'sample-1',
    user_id: 'sample',
    batch_id: BATCH,
    job_url: null,
    job_title: 'Engineering Manager — Platform Infrastructure',
    company: 'Razorpay',
    jd_text: '',
    ats_score: 82,
    role_level_score: 88,
    composite_score: 85,
    verdict: 'STRONG',
    hard_reject_reasons: [],
    analysis_json: {
      ats_score: 82,
      role_level_score: 88,
      composite_score: 85,
      verdict: 'STRONG',
      hard_reject_triggered: false,
      hard_reject_reasons: [],
      headline: 'Strong match — payments infra background transfers well, team size aligns with your experience.',
      matching_skills: ['Java', 'Kafka', 'AWS', 'Distributed Systems', 'Team Leadership', 'PostgreSQL'],
      missing_skills: ['Go', 'Kubernetes'],
      requirements_met: [
        { requirement: '8+ years of engineering experience', status: 'met', evidence: 'Your profile shows 10+ years' },
        { requirement: 'EM with 8+ direct reports', status: 'met', evidence: 'Matches your team size history' },
        { requirement: 'Payments or fintech domain', status: 'met', evidence: 'Listed in your preferences' },
        { requirement: 'Go or Rust experience', status: 'missing', evidence: 'Not found on your profile' },
      ],
      soft_concerns: [],
      role_level_assessment: 'Scope and team size are a direct match. The seniority bar here fits your current level.',
      gap_analysis: 'Go is preferred but not a blocker — your Java/JVM background transfers. Pick up basic Go syntax before the interview.',
      recommendation: 'APPLY. Strongest match in this batch. Infrastructure scope, fintech domain, and team size all align. Worth time investment.',
    },
    created_at: NOW,
  },
  {
    id: 'sample-2',
    user_id: 'sample',
    batch_id: BATCH,
    job_url: null,
    job_title: 'Senior Engineering Manager — Data Platform',
    company: 'Meesho',
    jd_text: '',
    ats_score: 71,
    role_level_score: 79,
    composite_score: 75,
    verdict: 'DECENT',
    hard_reject_reasons: [],
    analysis_json: {
      ats_score: 71,
      role_level_score: 79,
      composite_score: 75,
      verdict: 'DECENT',
      hard_reject_triggered: false,
      hard_reject_reasons: [],
      headline: 'Decent fit — data platform experience is adjacent, but Spark expertise is a gap.',
      matching_skills: ['Python', 'AWS', 'Team Leadership', 'SQL', 'Microservices'],
      missing_skills: ['Apache Spark', 'Flink', 'Data Warehousing'],
      requirements_met: [
        { requirement: '6+ years as EM', status: 'met', evidence: 'Matches your profile' },
        { requirement: 'Data platform or analytics infra', status: 'partial', evidence: 'Adjacent experience, not primary domain' },
        { requirement: 'Apache Spark or Flink', status: 'missing', evidence: 'Not found on your profile' },
        { requirement: 'E-commerce or consumer tech', status: 'met', evidence: 'Domain overlap found' },
      ],
      soft_concerns: ['Data platform depth may be interrogated heavily in the interview loop'],
      role_level_assessment: 'Level is right, but data-specific depth may be tested. Budget 1-2 weeks to study the stack.',
      gap_analysis: 'Spark is central to this role. Worth closing that gap if you want to pursue data platform as a domain.',
      recommendation: 'APPLY IF you\'re interested in the data domain. Be upfront about the Spark gap and show a learning plan.',
    },
    created_at: NOW,
  },
  {
    id: 'sample-3',
    user_id: 'sample',
    batch_id: BATCH,
    job_url: null,
    job_title: 'Engineering Manager — Mobile',
    company: 'PhonePe',
    jd_text: '',
    ats_score: 65,
    role_level_score: 80,
    composite_score: 73,
    verdict: 'DECENT',
    hard_reject_reasons: [],
    analysis_json: {
      ats_score: 65,
      role_level_score: 80,
      composite_score: 73,
      verdict: 'DECENT',
      hard_reject_triggered: false,
      hard_reject_reasons: [],
      headline: 'Decent fit — strong EM seniority, but mobile-specific skills are missing.',
      matching_skills: ['Team Leadership', 'Agile', 'Stakeholder Management', 'Kotlin'],
      missing_skills: ['iOS', 'React Native', 'Mobile CI/CD', 'App Performance Tooling'],
      requirements_met: [
        { requirement: '5+ years EM experience', status: 'met', evidence: 'Clear match' },
        { requirement: 'Android or iOS engineering background', status: 'partial', evidence: 'Kotlin listed, no iOS' },
        { requirement: 'Mobile CI/CD (Bitrise, Fastlane)', status: 'missing', evidence: 'Not on your profile' },
        { requirement: 'Consumer-facing app experience', status: 'met', evidence: 'Domain overlap' },
      ],
      soft_concerns: ['Mobile-first company — may expect hands-on mobile debugging knowledge'],
      role_level_assessment: 'Your seniority is right. But mobile-specific depth will be tested in system design rounds.',
      gap_analysis: 'If your teams have shipped mobile features, highlight that. Otherwise, mobile depth is a real gap here.',
      recommendation: 'APPLY IF your background includes shipping mobile features. Otherwise this requires significant prep.',
    },
    created_at: NOW,
  },
  {
    id: 'sample-4',
    user_id: 'sample',
    batch_id: BATCH,
    job_url: null,
    job_title: 'Head of Engineering — Logistics',
    company: 'Delhivery',
    jd_text: '',
    ats_score: 44,
    role_level_score: 58,
    composite_score: 52,
    verdict: 'WEAK',
    hard_reject_reasons: [],
    analysis_json: {
      ats_score: 44,
      role_level_score: 58,
      composite_score: 52,
      verdict: 'WEAK',
      hard_reject_triggered: false,
      hard_reject_reasons: [],
      headline: 'Weak fit — logistics domain and supply-chain systems are very different from your background.',
      matching_skills: ['Team Leadership', 'AWS', 'Microservices'],
      missing_skills: ['Supply Chain Systems', 'Route Optimization', 'WMS/TMS', 'Logistics Domain', 'IoT'],
      requirements_met: [
        { requirement: 'Logistics or supply chain domain', status: 'missing', evidence: 'No logistics experience on profile' },
        { requirement: 'Real-time routing or tracking systems', status: 'missing', evidence: 'Not found' },
        { requirement: 'EM with 10+ reports', status: 'partial', evidence: 'Team size is borderline' },
        { requirement: 'WMS or TMS platform experience', status: 'missing', evidence: 'Not found' },
      ],
      soft_concerns: ['Domain switch from product/payments to logistics ops is a significant narrative challenge'],
      role_level_assessment: 'The seniority bar is reachable, but domain mismatch is the primary issue here.',
      gap_analysis: 'Logistics is a deep domain — not just a tech role. Would require significant context-building.',
      recommendation: 'SKIP. Domain mismatch is too wide. Not worth the application time unless logistics is a deliberate pivot.',
    },
    created_at: NOW,
  },
  {
    id: 'sample-5',
    user_id: 'sample',
    batch_id: BATCH,
    job_url: null,
    job_title: 'Senior Software Architect — .NET Platform',
    company: 'Wipro Technologies',
    jd_text: '',
    ats_score: 0,
    role_level_score: 0,
    composite_score: 0,
    verdict: 'REJECT',
    hard_reject_reasons: ['Requires .NET — flagged as tech stack dealbreaker'],
    analysis_json: {
      ats_score: 0,
      role_level_score: 0,
      composite_score: 0,
      verdict: 'REJECT',
      hard_reject_triggered: true,
      hard_reject_reasons: ['Requires .NET — flagged as tech stack dealbreaker'],
      headline: 'Auto-rejected — .NET is in your tech dealbreakers list.',
      matching_skills: [],
      missing_skills: [],
      requirements_met: [],
      soft_concerns: [],
      role_level_assessment: '',
      gap_analysis: '',
      recommendation: 'SKIP. Hard-rejected by your rules before scoring. No further analysis needed.',
    },
    created_at: NOW,
  },
]
